worker_processes  1;
daemon off;
master_process off;

error_log  logs/tlcp-error.log debug;
pid        logs/tlcp.pid;

events {
    worker_connections  64;
}

http {
    access_log logs/tlcp-access.log;

    server {
        listen 8445 ssl;
        server_name localhost;

        ssl_protocols TLCP;
        ssl_certificate tlcp-certs/double_certs.pem;
        ssl_certificate_key tlcp-certs/double_keys.pem;
        ssl_password_file pass.txt;

        root html;
    }
}
