worker_processes  1;
daemon off;
master_process off;

error_log  logs/tlcp-error.log debug;
pid        logs/tlcp.pid;

events {
    worker_connections  64;
}

http {
    access_log logs/tlcp-access.log;

    server {
        listen 8445 ssl;
        server_name localhost;

        ssl_protocols TLCP;
        ssl_certificate /Users/guanzhi/code/github/GmSSL-Nginx/nginx-1.30.2/gmssl-tests/tlcp-certs/double_certs.pem;
        ssl_certificate_key /Users/guanzhi/code/github/GmSSL-Nginx/nginx-1.30.2/gmssl-tests/tlcp-certs/double_keys.pem;
        ssl_password_file /Users/guanzhi/code/github/GmSSL-Nginx/nginx-1.30.2/gmssl-tests/pass.txt;

        root /Users/guanzhi/code/github/GmSSL-Nginx/nginx-1.30.2/gmssl-tests/html;
    }
}
